# Generated by Django 2.1 on 2018-08-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_api', '0002_auto_20180808_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
